Week 6 zack
learn-academy-2022-foxtrot/week-6-assessment-ZackRohde pull request #1
Opened 2022-10-21 19:22 UTC by ZackRohde

# Submitting Week 6 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [✅  ] Coding Challenges
- [✅  ] Coding Concepts
- [ ✅ ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here: I felt great on the interview question and the rails commenting for the most part if you could correct anything that isnt correct that'd be great to study up on. For the JavaScript, the first one is completely over my head and knowledge I feel without copying code. I again think I understand the logic of majority of the question, but lack of experience is killing me.

2022-10-26 23:33 UTC, elysemontano requested changes
Request changes: I would really like to see a little more on problem 1 in code challenges.  I left some feedback to consider in working through it.  If you are still struggling, please reach out and we can set up a time to work through this problem together.  

Other comments: All other sections were excellent!  I can certainly tell that you really shine with working on backend development concepts.  Keep that momentum up!

2022-10-26 23:33 UTC, elysemontano commented on code-challenges.test.js
> +// I know well use string interpolation to access the name and occupation and use it for the return
Consider that you have an array of objects.  If you iterate on the array, you will be accessing an individual object which then you can utilize dot notation to access the values in the object.  If you get really stuck on a question, please reach out!  Don't suffer in silence.

2022-10-26 23:33 UTC, elysemontano commented on code-challenges.test.js
> +const sumOfNumCubed = (array) => {
Nice work on these last 2 problems!

2022-10-26 23:33 UTC, elysemontano commented on interview-questions.md
> +Researched answer: I believe my way for fixing it is by adding a column, otherwise I'm unsure what to search to fix this mistake. Foreign keys and primary keys must always be connected so, the more t
You would want to generate a migration to be able to add a column.

2022-10-26 23:33 UTC, elysemontano commented on interview-questions.md
> +User Story 1: As a developer I want to create my application using my preffered languages.
Really excellent work in this section!

2022-10-26 23:33 UTC, elysemontano commented on rails-commenting.rb
> +  # Were defining new which is a controller action. post is the instance variable. BlogPost is the class and the .new is giving the instance variable the ability to be viewed?
I am assuming the question mark here is asking for validation, and yes your are correct!

2022-10-26 23:33 UTC, elysemontano commented on rails-commenting.rb
> +# Application Controller is the Parent Class and the BlogPostController is a Child Class.
Crushed this section!!

2022-10-27 01:41 UTC, ZackRohde commented on code-challenges.test.js
> +// I know well use string interpolation to access the name and occupation and use it for the return
I believe I did it, but I can't get it to pass. It really helped understanding what was actually needed. I have a hard time understanding exactly what's being asked I find it too vague, I need more direction.

2022-10-27 17:38 UTC, elysemontano approved these changes
Great work on the changes on problem 1!!

2022-10-27 17:38 UTC, elysemontano commented on code-challenges.test.js
> +  return array.map((object) => `${object.name.split("").map((firstName) => firstName.slice(0, 1).toUpperCase() + firstName.slice(1)).join("")} is ${object.occupation}.`
This looks great! Thank you for adding those changes!

2022-10-27 23:01 UTC, merged